### PR TITLE
Unit testing with JUnit

### LINKED ISSUE #11: Unit tests with JUnit
https://kotlinlang.org/docs/jvm-test-using-junit.html

### PR DESCRIPTION
**Pull request by BD103**
Closes #11.

Unit testing is an automated system for testing individual portions of your codebase. They allow you to setup tests that assert that something is true. For instance:

```kotlin
import kotlin.test.Test
import kotlin.test.assertEquals

internal class DemoTest {
    @Test
    fun demoTest() {
        // Checks that 1 + 2 = 3.
        assertEquals(3, 1 + 2)
    }
}
```

This test will check that 1 + 2 = 3. If that is ever not the case, the test will fail. We can use this to verify that logic remains remains consistent across changes. For a more concrete example:

```kotlin
// Returns true if `this` is null.
fun <T> T?.isNull(): Boolean = this == null

@Test
fun testIsNull() {
    val x: Int? = null
    assertTrue(x.isNull())

    val y: Int? = 1
    assertFalse(x.isNull())
}
```

If `isNull` is ever changed incorrectly, the tests will fail and we will know about it.

### CODE REVIEW

**Comment by BD103** [comment]
Tests are currently run twice: once for Java and once for Kotlin. I need to dig deeper to only run Kotlin tests before this can be marked as ready for review.

**Comment by BD103** [comment]
Update: just run the `testDebugUnitTest` task instead of `test` or `check`.

**Review by cadenceforney — APPROVED** [review]
looks good! I enjoyed the comments.

**Comment by BD103** [comment]
I added a section to "How to test a pull request" on running unit tests. [Here it is.](https://github.com/BotsBurgh/BOTSBURGH-FTC-2024-25/wiki/How-to-test-a-pull-request#running-unit-tests)

Thanks, merging!

**Pull request merged**
