### PR TITLE
Update to `FtcRobotController` 10.1

### LINKED ISSUE #40: Update to `FtcRobotController` 9.2
- [Release notes](https://github.com/FIRST-Tech-Challenge/FtcRobotController?tab=readme-ov-file#version-92-20240701-085519)
- [Tag](https://github.com/FIRST-Tech-Challenge/FtcRobotController/releases/tag/v9.2)

### PR DESCRIPTION
**Pull request by BD103**
Closes #40 and #74.

I did this by checking out [the repository](https://github.com/FIRST-Tech-Challenge/FtcRobotController) and generating a diff for all of the files we have no modified with:

```bash
git diff v9.1 v9.2 -- path/to/folders > ftc.diff
```

And then in this repository I called:

```bash
git apply path/to/ftc.diff
```

For all other changes (such as to `build.dependencies.gradle`), I copied them over manually by inspecting https://github.com/FIRST-Tech-Challenge/FtcRobotController/compare/v9.1...v9.2.

### CODE REVIEW

**Comment by BD103** [comment]
Before this is merged, I need to make sure that FTC Dashboard and Road Runner do not need to be updated.

**Review by cadenceforney — APPROVED** [review]
looks good I do not know if the ftc dashboard or road runner need to be updated though

**Comment by BD103** [comment]
Blocked by https://github.com/acmerobotics/ftc-dashboard/pull/154.

**Comment by BD103** [comment]
The blocking PR has been merged, now we're just waiting for it to be released.

**Comment by BD103** [comment]
I'm updating this to also upgrade to version 10.1.

**Pull request merged**
