### PR TITLE
Create `API` class

### LINKED ISSUE #4: Migrate `API` class
Last year's `API` class can be found [here].

[here]: https://github.com/BotsBurgh/BOTSBURGH-FTC-2023-24/blob/457483751af7fa941e585ce53c3079d9ef7ac94f/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/API.kt

This year, we need it to support the following things:

- Access the current `OpMode` without passing the object into every function.
- Support running code when an `OpMode` is initialized.
- Support running code when an `OpMode` is stopped.
- Access `LinearOpMode`-specific functions, with possible fallbacks / errors if unavailable.
- Specify API dependencies.
- Reset variables so old configuration does not persist across runs.
  - If possible, this should be automated and invisible.

### PR DESCRIPTION
**Pull request by BD103**
Closes #4.

- [x] Access the current OpMode without passing the object into every function.
- [x] Support running code when an OpMode is initialized.
- [x] ~~Support running code when an OpMode is stopped.~~
  - Skipped for now, will be implemented if needed.
- [x] Access LinearOpMode-specific functions, with possible fallbacks / errors if unavailable.
- [x] Specify API dependencies.
- [x] Reset variables so old configuration does not persist across runs.

### CODE REVIEW

**Review by SnipSnek — COMMENTED** [review]
pls add more comments to 1, 2, 3, and 4 for explanation

also code works  💀

**Review by cadenceforney — DISMISSED** [review]
More Comments

**Review by Vif15 — APPROVED** [review]

**Comment by BD103** [comment]
Tests need to be added for these types, but I'm going to implement them in a follow up PR. Too much is blocked by this right now.

**Review by Vif15 — APPROVED** [review]
💀

**Pull request merged**
